#  ______ _                                _
# |  ____(_)                              | |
# | |__   _ _ __ ___  ___ _ __   __ _ _ __| | _____
# |  __| | | '__/ _ \/ __| '_ \ / _` | '__| |/ / __|
# | |    | | | |  __/\__ \ |_) | (_| | |  |   <\__ \
# |_|    |_|_|  \___||___/ .__/ \__,_|_|  |_|\_\___/
#                        | |
#                        |_|
#
#           Firesparks plugin configuration
#          Proceed with caution if you don't
#               know what you're doing.

# Basic mechanics affecting comfort.
comfort:
  growth-amount: 6
  progressbar-name: "&lComfort"

# Enables coldness. Players wearing armor will not freeze.
coldness:
  enable: true

# Burning of items in a campfire. [Right-click on the campfire with an item]
# After burning an item in a campfire, the effect of the potion begins to act in a certain radius, like a beacon.
#
# Valid materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Valid potion effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
item-burn:
  enable: true
  item-list:
    DANDELION:
      effect: SLOW
      duration: 60
      time-to-burn: 25
      color: '#778899'

# Plugin's messages.
messages:
  message-of-the-day:
    - "&7It's getting cold!~"
    - "&7What a beautiful day."
    - "&7Imagine the smell."
    - "&7Have you tried it yet?"

  item-burn:
    - "&7You feel a little dizzy..."
    - "&7Your whole body is relaxing."
    - "&7The aroma coming from the campfire makes you euphoric..."
  campfire-no-capacity: "&7This campfire is occupied by other item."
  getting-cold: "&7It's cold... Find a way to keep warm or put on some clothes."
  delightfulness: "&7You feel well rested..."